package com.freemarker.hello.templates;

public class TableMeta {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.table_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.column_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String columnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.camel_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String camelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.camel_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String upperName;

    public String getUpperName() {
        return upperName;
    }

    public void setUpperName(String upperName) {
        this.upperName = upperName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.type
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.priority
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.sort
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.visible
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private Integer inVisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.render
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String render;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.search
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private Integer search;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.add
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private Integer add;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.edit
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private Integer edit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.code_id
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String codeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.primary_key
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private Integer primaryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_meta.foreign_key
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    private String foreignKey;
    private String foreignName;

    private String foreignTable;

    public String getForeignName() {
        return foreignName;
    }

    public void setForeignName(String foreignName) {
        this.foreignName = foreignName;
    }

    public String getForeignTable() {
        return foreignTable;
    }

    public void setForeignTable(String foreignTable) {
        this.foreignTable = foreignTable;
    }

    private Integer readOnly;

    public Integer getReadOnly() {
        return readOnly;
    }

    public void setReadOnly(Integer readOnly) {
        this.readOnly = readOnly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.table_name
     *
     * @return the value of table_meta.table_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.table_name
     *
     * @param tableName the value for table_meta.table_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.column_name
     *
     * @return the value of table_meta.column_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.column_name
     *
     * @param columnName the value for table_meta.column_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.camel_name
     *
     * @return the value of table_meta.camel_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public String getCamelName() {
        return camelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.camel_name
     *
     * @param camelName the value for table_meta.camel_name
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setCamelName(String camelName) {
        this.camelName = camelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.type
     *
     * @return the value of table_meta.type
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.type
     *
     * @param type the value for table_meta.type
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.priority
     *
     * @return the value of table_meta.priority
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.priority
     *
     * @param priority the value for table_meta.priority
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.sort
     *
     * @return the value of table_meta.sort
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.sort
     *
     * @param sort the value for table_meta.sort
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.visible
     *
     * @return the value of table_meta.visible
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public Integer getInVisible() {
        return inVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.visible
     *
     * @param inVisible the value for table_meta.visible
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setInVisible(Integer inVisible) {
        this.inVisible = inVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.render
     *
     * @return the value of table_meta.render
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public String getRender() {
        return render;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.render
     *
     * @param render the value for table_meta.render
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setRender(String render) {
        this.render = render;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.search
     *
     * @return the value of table_meta.search
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public Integer getSearch() {
        return search;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.search
     *
     * @param search the value for table_meta.search
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setSearch(Integer search) {
        this.search = search;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.add
     *
     * @return the value of table_meta.add
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public Integer getAdd() {
        return add;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.add
     *
     * @param add the value for table_meta.add
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setAdd(Integer add) {
        this.add = add;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.edit
     *
     * @return the value of table_meta.edit
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public Integer getEdit() {
        return edit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.edit
     *
     * @param edit the value for table_meta.edit
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setEdit(Integer edit) {
        this.edit = edit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.code_id
     *
     * @return the value of table_meta.code_id
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.code_id
     *
     * @param codeId the value for table_meta.code_id
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.primary_key
     *
     * @return the value of table_meta.primary_key
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public Integer getPrimaryKey() {
        return primaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.primary_key
     *
     * @param primaryKey the value for table_meta.primary_key
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setPrimaryKey(Integer primaryKey) {
        this.primaryKey = primaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_meta.foreign_key
     *
     * @return the value of table_meta.foreign_key
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public String getForeignKey() {
        return foreignKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_meta.foreign_key
     *
     * @param foreignKey the value for table_meta.foreign_key
     *
     * @mbggenerated Wed Jul 22 16:25:57 CST 2020
     */
    public void setForeignKey(String foreignKey) {
        this.foreignKey = foreignKey;
    }

    @Override
    public String toString() {
        return "TableMeta{" +
                "tableName='" + tableName + '\'' +
                ", columnName='" + columnName + '\'' +
                ", camelName='" + camelName + '\'' +
                ", type='" + type + '\'' +
                ", priority=" + priority +
                ", sort=" + sort +
                ", inVisible=" + inVisible +
                ", render='" + render + '\'' +
                ", search=" + search +
                ", add=" + add +
                ", edit=" + edit +
                ", codeId='" + codeId + '\'' +
                ", primaryKey=" + primaryKey +
                ", foreignKey='" + foreignKey + '\'' +
                '}';
    }
}